import { getSessionUserWithRole, jsonOk, jsonError } from '@/lib/api-helpers';
import { createAdminClient } from '@/lib/supabase/admin';
import { RESTOCK_STATUSES } from '@/lib/constants';
import { convert } from '@/lib/currency';
import { FALLBACK_RATES } from '@/lib/constants';

export async function GET() {
  const session = await getSessionUserWithRole();
  if (!session) return jsonError('Unauthorized', 401);

  const admin = createAdminClient();
  const { data, error } = await admin
    .from('sales')
    .select('*')
    .eq('business_id', session.businessId)
    .order('date', { ascending: false });
  if (error) return jsonError(error.message);
  return jsonOk(data);
}

export async function POST(request: Request) {
  const session = await getSessionUserWithRole();
  if (!session) return jsonError('Unauthorized', 401);
  if (!['Administrator', 'Manager', 'Sales Staff'].includes(session.role)) return jsonError('Forbidden', 403);

  const body = await request.json();
  if (!body.product_id) return jsonError('Product is required.');

  const admin = createAdminClient();

  // Fetch the product — scoped to this business
  const { data: product, error: prodErr } = await admin
    .from('products')
    .select('id, stock_qty, cost_price, currency')
    .eq('id', body.product_id)
    .eq('business_id', session.businessId)
    .single();
  if (prodErr || !product) return jsonError('Product not found.', 404);

  const isRestockStatus = RESTOCK_STATUSES.includes(body.status ?? 'Pending');
  const qty             = body.qty ?? 1;

  // Stock check (only for active statuses)
  if (!isRestockStatus && product.stock_qty < qty) {
    return jsonError(
      `Only ${product.stock_qty} unit(s) of this product are in stock. ` +
      `Use force=true to override.`,
      409,
    );
  }

  // Deduct stock for active statuses
  let stockDeducted = false;
  if (!isRestockStatus) {
    const newQty = product.stock_qty - qty;
    const { error: stockErr } = await admin
      .from('products')
      .update({ stock_qty: newQty })
      .eq('id', body.product_id)
      .eq('business_id', session.businessId);
    if (stockErr) return jsonError(stockErr.message);
    const { error: adjErr } = await admin.from('inventory_adjustments').insert({
      date:        body.date ?? new Date().toISOString().slice(0, 10),
      product_id:  body.product_id,
      qty_change:  -qty,
      reason:      `Sale (invoice TBD)`,
      source_type: 'sale',
      business_id: session.businessId,
      created_by:  session.userId,
    });
    if (adjErr) return jsonError(adjErr.message);
    stockDeducted = true;
  }

  // Insert sale (invoice_number generated by DB default)
  const { data: sale, error: saleErr } = await admin
    .from('sales')
    .insert({
      date:           body.date,
      customer_id:    body.customer_id || null,
      product_id:     body.product_id,
      qty,
      unit_price:     body.unit_price ?? 0,
      discount:       body.discount ?? 0,
      tax:            body.tax ?? 0,
      shipping_fee:   body.shipping_fee ?? 0,
      currency:       body.currency ?? 'USD',
      payment_method: body.payment_method ?? 'Cash',
      channel:        body.channel ?? 'Physical Store',
      status:         body.status ?? 'Pending',
      stock_deducted: stockDeducted,
      business_id:    session.businessId,
      created_by:     session.userId,
    })
    .select()
    .single();
  if (saleErr) return jsonError(saleErr.message);

  // Update inventory_adjustment with real invoice number
  if (stockDeducted) {
    await admin.from('inventory_adjustments')
      .update({ reason: `Sale ${sale.invoice_number}`, source_id: sale.id })
      .eq('source_type', 'sale')
      .is('source_id', null)
      .eq('created_by', session.userId)
      .eq('business_id', session.businessId)
      .order('created_at', { ascending: false })
      .limit(1);
  }

  // Update customer stats
  if (body.customer_id) {
    const { data: cust } = await admin
      .from('customers')
      .select('total_orders, total_spent_usd')
      .eq('id', body.customer_id)
      .eq('business_id', session.businessId)
      .single();
    if (cust) {
      const orders     = (cust.total_orders ?? 0) + 1;
      const spentUSD   = (cust.total_spent_usd ?? 0) + convert(sale.net_sales, sale.currency, 'USD', FALLBACK_RATES);
      const classification =
        orders >= 5  ? 'VIP Customer' :
        orders > 1   ? 'Repeat Customer' :
                       'New Customer';
      await admin.from('customers').update({
        total_orders:       orders,
        total_spent_usd:    spentUSD,
        last_purchase_date: sale.date,
        classification,
      }).eq('id', body.customer_id);
    }
  }

  return jsonOk(sale, 201);
}
